### ISSUE TITLE
Consider supporting Compose Desktop?

### ISSUE THREAD

**Issue by glureau** [usuiat/Zoomable#109]
I've made a copy of the 2 files in my desktop project, by removing the "fast" variants of `any` and `forEach` I got something working very quickly. Just wanted to share that quick experiment.

**Comment by usuiat** [comment]
Thank you for sharing!
There are no plans to support Compose Desktop at this time, but I am very interested. 
So I am happy to hear that this library will be available for desktop as well with only a few changes 😄

**Comment by glureau** [comment]
Just FYI I've eventually found a Compose multiplatform implementation there: https://github.com/mxalbert1996/Zoomable also the api is quite different and I did not try it yet.

**Comment by usuiat** [comment]
This is interesting. I will refer to it when I make my Zoomable multi-platform compatible.
Thanks!

**Comment by panpf** [comment]
I recommend a similar image zooming library ZoomImage (https://github.com/panpf/zoomimage).

It perfectly supports Compose Multiplatform and Android View, supports zooming, panning, positioning, rotation, and subsampling of large images. It also integrates image loaders such as sketch, glide, picasso, coil, etc.

The most important thing is that it can zoom large images without memory overflow
