### ISSUE TITLE
Support lower compileSdk version

### ISSUE THREAD

**Issue by Ten-Wang** [usuiat/Zoomable#117]
Hi,

I came across this library, and I'm really impressed with its design. However, I'm facing an issue with importing it into my project due to its dependency on 'androidx.emoji2:emoji2:1.4.0,' which requires an update to compile version 34. This dependency seems unrelated to the primary purpose of this library, which feels a bit unusual.

Additionally, upgrading my current project to compileSdk version 34 is quite time-consuming. 

Therefore, I would like to inquire if it's possible for the library to provide documentation support for lower versions, like compileSdk version 33. I'm wondering if this request is feasible.

Thank you.

**Comment by usuiat** [comment]
@Ten-Wang 
Thank you for your interest in this library.
You can use Zoomable v1.4.3 if you want to use compileSdk version 33.

Zoomable depends on compose.foundation. And compose.foundation depends on emoji2. Therefore Compose v1.5 require compileSdk 34.
If you want to use compileSdk version 33, you should use Compose v1.4.x. It's same for Zoomable.
