### ISSUE TITLE
Notify on scale changes

### ISSUE THREAD

**Issue by pkrystyniak-jt** [usuiat/Zoomable#148]
Hey,
I have an UI element over the zoomable Image, that I want to hide or show depending if the image is zoomed in or out.
I don't see a direct way to observe the scale changes at this moment. Would it be possible to f.e. add a callback for scale changes?

**Comment by usuiat** [comment]
Hi, @pkrystyniak-jt 
Could you explain in a little more detail?
Is it not enough to observe ZoomState.scale?

**Comment by pkrystyniak-jt** [comment]
> Hi, @pkrystyniak-jt Could you explain in a little more detail? Is it not enough to observe ZoomState.scale?

In my scenario I want a certain Ui element to disappear when the Image is zoomed in either with double tap or pinch gesture.  Yes, `ZoomState.scale` is a property that I'm interested in, but is there a way to _observe it's changes_ already?
