### ISSUE TITLE
Enable zoom

### ISSUE THREAD

**Issue by T8RIN** [usuiat/Zoomable#151]
Ability to enable/disable zoom would be really nice

**Comment by T8RIN** [comment]
Like here https://github.com/SmartToolFactory/Compose-Zoom

**Comment by usuiat** [comment]
@T8RIN 
Thank you for your suggestion. I agree that the enable/disable feature is useful. I will consider adding this feature.

**Comment by T8RIN** [comment]
Thanks :)

**Comment by usuiat** [comment]
I added zoomEnabled parameter.
The library you introduced had an implementation that asked enable/disable every time PointerInput occurred, but I decided that it was too much for Zoomable, so I made a simple implementation.

**Comment by T8RIN** [comment]
Okay, what's about another commits?👀
