### ISSUE TITLE
Zoom on double tap

### ISSUE THREAD

**Issue by T8RIN** [usuiat/Zoomable#152]
```kotlin
onDoubleTap = { position ->
    when (zoomState.scale) {
        in 1f..<5f -> {
            zoomState.changeScale(5f, position)
        }
        in 5f..<10f -> {
            zoomState.changeScale(10f, position)
        }
        else -> {
            zoomState.changeScale(1f, position)
        }
    }
}
```

if there will be parameter `level`, then it will be easeir to manage, like

```kotlin
onDoubleTap = { position, level ->
    when (level) {
        ZoomLevel.Min -> {
            zoomState.changeScale(1f, position)
        }
        ZoomLevel.Mid-> {
            zoomState.changeScale(5f, position)
        }
        ZoomLevel.Max-> {
            zoomState.changeScale(10f, position)
        }
    }
}
```

**Comment by T8RIN** [comment]
![image](https://github.com/usuiat/Zoomable/assets/52178347/e37e61bd-15db-4bba-93b7-63260475bb23)

Like this, but zoomState need to expand its internal maxZoom parameter and also include minZoom one

**Comment by usuiat** [comment]
@T8RIN 
I do not think it is a good idea to fix the number of steps of `level` to 3.
Different apps have different requirements for double-tap behavior.
Therefore, Zoomable provides a double-tap handler without enforcing a specific number of steps.

In fact, many apps, such as Google Photo and X, change scale in two steps with a double tap. 
This is why Zoomable's default double-tap handler is implemented in two steps.

**Comment by T8RIN** [comment]
Hm, with this implementation add two leveled way easier, maybe just add additional modifier?

**Comment by T8RIN** [comment]
Okay, i will remove it, and create additional zoom handler param

**Comment by T8RIN** [comment]
Done @usuiat
