### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by T8RIN** [usuiat/Zoomable#154]
Is it possible to add rotation? (i know it is :))

**Comment by T8RIN** [comment]
![image](https://github.com/usuiat/Zoomable/assets/52178347/681b69f8-d776-481c-b338-5d591c099a84)

![image](https://github.com/usuiat/Zoomable/assets/52178347/231cc37d-e8dd-44f8-8269-5ba2b641e034)


This can be used as API reference, enable lambda gets zoom, pan, rotation and says to zoomable state should it update layout or intercept pointers to not go throught it, this is usefult in pagers, like each image is zoomed, but if it's not you can scroll

**Comment by T8RIN** [comment]
I don't like library that i provided firstly because it zooms very ugly and not in action performed place, instead in screen center and this is annoying

**Comment by usuiat** [comment]
@T8RIN 
Thank you for your suggestion.
I know it's possible to rotate the element. But I don't see the need for that feature.

**Comment by usuiat** [comment]
I will close this Issue because rotation does not fit the use case envisioned by this library.
