### ISSUE TITLE
Support for zooming only when pinching

### ISSUE THREAD

**Issue by T8RIN** [usuiat/Zoomable#155]
this is usable in painting mode, you can paint by finger and also zoom in by two fingers

**Comment by T8RIN** [comment]
Mine implements custom modifier and i struggled to get zoom built in but failed :( so i just use separate zoomable modifier now

**Comment by usuiat** [comment]
The purpose of this library is to easily achieve zooming, not to achieve complex behavior like that of a paint application.
I'm sorry I cannot meet your request.
