### ISSUE TITLE
Support for boundary clip

### ISSUE THREAD

**Issue by T8RIN** [usuiat/Zoomable#156]
We can now use 

```kotlin
Modifier
   .clipToBounds()
   .zoomable(zoomState = zoomState)
```

but it will be good if we can use it like that

```kotlin
Modifier
   .zoomable(
        zoomState = zoomState, 
        clip = true
   )
```

**Comment by usuiat** [comment]
I agree that zoomable and clip are often used together.
However, clip processing is independent from zoomable processing.
Therefore, I don't think clip functionality should be added to zoomable.
