### ISSUE TITLE
make zoomable image like instagram posts

### ISSUE THREAD

**Issue by Hamidreza-mj** [usuiat/Zoomable#162]
how can i implement image zoom like instagram posts it's set scale to 1f after pinch is released.

**Comment by usuiat** [comment]
@Hamidreza-mj 
Unfortunately, Zoomable's current API does not allow for Instagram-like behavior.
It is necessary to add a callback to notify that the gesture has ended.

**Comment by aeiou-st** [comment]
> how can i implement image zoom like instagram posts it's set scale to 1f after pinch is released.

@usuiat If you can do something for this please look into your spare time.

**Comment by usuiat** [comment]
@Hamidreza-mj @aeiou-st 
I've just published [v1.7.0-beta01](https://github.com/usuiat/Zoomable/releases/tag/v1.7.0-beta01).
Please try to use `Modifier.snapBackZoomable`.
Thanks 😄

**Comment by Hamidreza-mj** [comment]
@usuiat 
Thank you for making this changes
