### ISSUE TITLE
How ZoomState exposes offsetX, offsetY and scale so i can find what part of the image is being displayed. 

### ISSUE THREAD

**Issue by osw-mj** [usuiat/Zoomable#190]
### **Here is the explanation with example:**

> Suppose I've image A that is have full human body image and now using this library i've done zoomed to face and i've the button that will take me to next screen with image but that image should show me the image that I've zoomed to face not the old one of full body image.

**Comment by osw-mj** [comment]
Hey @usuiat How are you,
Sorry but can you look into my question, Let me know what you think about this.
Or do you have any confusion?
Response this comments if you read it.

**Comment by usuiat** [comment]
@osw-mj 
Sorry for the late reply.
`ZoomState` exposes `offsetX`, `offsetY` and `scale`.
Using these properties, we may be able to guess which part of the image is being displayed.
Please let me know if there are any other properties you need.

**Comment by osw-mj** [comment]
Yes same i want to know the part displayed and want to convert that part into the image file

**Comment by usuiat** [comment]
The figure shows the `scale`, `offsetX`, and `offsetY` when the blue image size is zoomed to orange.
<img width="500" alt="image" src="https://github.com/usuiat/Zoomable/assets/17829294/4f568bd1-1dc6-4142-98bc-a54cce13795f">

The visible area then becomes a green rectangle, which can be represented by the equation in the figure.

<img width="500" alt="image" src="https://github.com/usuiat/Zoomable/assets/17829294/398706fb-5f1b-4c6a-a6a0-ca5088a52186">

However, this is the case when the aspect ratio of the image and the display area match.
If the aspect ratios are different, it becomes more complicated.
Probably, the required rectangular area will vary from application to application.

**Comment by osw-mj** [comment]
It's there any function to get the visible rectangle offsets?

**Comment by osw-mj** [comment]
Okay I'm closing this issue for now. Thank you.
