### ISSUE TITLE
Key param

### ISSUE THREAD

**Issue by T8RIN** [usuiat/Zoomable#192]
It would be really helpful to have key parameter which by it's changing resets zoom state to initial position

**Comment by T8RIN** [comment]
in rememberZoomableState ofc

**Comment by T8RIN** [comment]
reset doesn't reset the state fully, isn't it?

**Comment by usuiat** [comment]
`reset()` does reset `scale`, `offsetX`, and `offsetY`.

**Comment by T8RIN** [comment]
And if i change the zoom container size, will it help to maintain usability?

**Comment by usuiat** [comment]
Changing `contentSize` will not reset the scale and offset.
I did not assume to change `contentSize` dynamically.
Do you want to change the image dynamically?

**Comment by usuiat** [comment]
@T8RIN 
Sorry for the late reply.
I will close this Pull Request.

If you want to recreate `ZoomState` by keys, you can instantiate `ZoomState` in `remember` function and pass keys to it.
The constructor of `ZoomState` is public.

```
remember(key) { ZoomState() }
```
