### ISSUE TITLE
[FR]: Support double-tap zoom

### ISSUE THREAD

**Issue by herbeth1u** [usuiat/Zoomable#51]
### Is there an existing issue for this?
 - [x] I have searched the existing issues
 
### Describe the problem
As of now, Zoomable supports a "double-tap + drag" zoom. Is it possible to support the arguably more usual "double-tap" zoom?
For example, it's a feature supported by [PhotoView](https://github.com/Baseflow/PhotoView) or Discord's image viewer.

### Describe the solution
How it works:
- Double-tap once: scale = max scale / 2
- Double-tap again: scale = max scale
- Double-tap again: resets zoom
See https://github.com/Baseflow/PhotoView/blob/master/photoview/src/main/java/com/github/chrisbanes/photoview/PhotoViewAttacher.java#L231

Thanks.

**Comment by usuiat** [comment]
Thanks for the proposal. @herbeth1u 
I agree that a double-tap zoom would be useful.

However, is the 3-step behaviour like PhotoView necessary?
I think the following 2-step behaviour is enough.

- Double-tap once: scale = 2.0
- Double-tap again: resets zoom

I checked the behavior of Google Photo, Twitter, Facebook, Discord, etc.
They all implement this 2-step behavior.

**Comment by herbeth1u** [comment]
How about making the number of steps configurable? If this is too overkill, settling on the 2-step behavior like most popular apps sounds like a reasonable plan as well.

**Comment by usuiat** [comment]
Noted.
We will consider how to implement it.

**Comment by cacato86** [comment]
How is the state of this feature? The library is awesome, but I'm missing this functionality 😞
