### ISSUE TITLE
This library exposes a BuildConfig in its public API. Consider disabling it.

### ISSUE THREAD

**Issue by StylianosGakis** [usuiat/Zoomable#98]
https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/dsl/BuildFeatures#buildconfig

**Comment by usuiat** [comment]
@StylianosGakis 
Thank you for creating an issue.
I am not very familiar with buildconfig, so could you confirm the change?
- #99

**Comment by StylianosGakis** [comment]
Ever since AGP 8.0 (I think) the field `android.defaults.buildfeatures.buildconfig` was flipped to by default be `false` anyway.
So what you can also try is to simply remove that line completely instead. Then check in a sample project which imports this library that the BuildConfig is in fact not being generated.

**Comment by StylianosGakis** [comment]
Ever since AGP 8.0 (I think) the field android.defaults.buildfeatures.buildconfig was flipped to by default be false anyway.
So yeah your fix must be enough as far as I am aware. Simply check in a sample project which imports this library that the BuildConfig is in fact not being generated and it should be all good.
